version: '3.8'

services:
  app:
    build: ./
    command: ./app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

  db:
    restart: always
    image: postgres:latest
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5436:5432"
    networks:
      - backend
networks:
  backend:
    driver: bridge